# Kopp14 Vertical Land Motion Pipeline

preprocess:
  task1:
    executable: "python3"
    pre_exec: "pip install --upgrade pip; pip install numpy scipy netCDF4 pyyaml"
    script: "GIA_caron18_preprocess.py"
    options:
      - "pipeline_id"
    upload_and_extract_input_data:
      - "caron18_GIA_preprocess_data.tgz"
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"


fit:
  task1:
    executable: "python3"
    pre_exec: []
    script: "GIA_caron18_fit.py"
    options:
      - "pipeline_id"


project:
  task1:
    executable: "python3"
    script: "GIA_caron18_project.py"
    options:
      - "pipeline_id"

postprocess:
  task1:
    executable: "python3"
    script: "GIA_caron18_postprocess.py"
    options:
      - "nsamps"
      - "seed"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - 'read_locationfile.py'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
